# Generated by Django 5.2.17 on 2026-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvieww', '0004_administrador_alter_producto_codigo_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='evidencias',
            field=models.CharField(max_length=255),
        ),
    ]
